name: "prometheus-grafana"
type: static
path: "./manifests"
subcomponents:
  - name: "grafana"
    type: helm
    source: "https://github.com/grafana/helm-charts"
    method: "git"
    path: "charts/grafana"
  - name: "prometheus"
    type: helm
    source: "https://github.com/prometheus-community/helm-charts/"
    method: "git"
    path: "charts/prometheus"
